# Numpy Exercises

## Exercise 1 (Employee Pay)

In [2]:
import numpy as np

# Number of hours worked by 8 employees (and hourly rate)
hours = np.array([35, 42, 38, 50, 29, 45, 40, 33])
hourly_rate = 22.50

pay = np.array(hours * hourly_rate)
print(f"Total pay for each employee: {np.round(pay, decimals=2)}")

print(f"Employees' pay amounts that were greater than 900: {pay[pay > 900]}")

employee_nums = np.arange(1, 9)
print(f"Employee IDs: {employee_nums}")

print(f"IDs of employees who worked 40 or more hours: {employee_nums[hours[employee_nums - 1] >= 40]}")

new_arr = np.where(hours < 40, hours, 40)
print(new_arr)

Total pay for each employee: [ 787.5  945.   855.  1125.   652.5 1012.5  900.   742.5]
Employees' pay amounts that were greater than 900: [ 945.  1125.  1012.5]
Employee IDs: [1 2 3 4 5 6 7 8]
IDs of employees who worked 40 or more hours: [2 4 6 7]
[35 40 38 40 29 40 40 33]


## Exercise 2 (Exam Gradebook)

In [ ]:
grades = np.array([
    [85, 92, 78, 90],
    [76, 88, 95, 82],
    [91, 79, 87, 94],
    [68, 74, 80, 77],
    [95, 89, 92, 96]
])

print(grades.dtype)
print(grades.shape)

print(f"All exam grades for student 4: {grades[3]}")

print(f"Exam 3 scores for every student: {grades[:, 2]}")

print(f"Grades for first 3 students on Exams 2 through 4: {grades[:3, 1: 4]}")

print(f"Every grade higher than 90: {grades[grades > 90]}")

print(f"All grades between 80 and 90 inclusive: {grades[(grades >= 80) & (grades <= 90)]}")

int64
(5, 4)
All exam grades for student 4: [68 74 80 77]
Exam 3 scores for every student: [78 95 87 80 92]
Grades for first 3 students on Exams 2 through 4: [[92 78 90]
 [88 95 82]
 [79 87 94]]
Every grade higher than 90: [92 95 91 94 95 92 96]
All grades between 80 and 90 inclusive: [85 90 88 82 87 80 89]


## Question 3 (Fixing Sensor Data)

In [19]:
temperatures = np.array([
    [72, 74, 105, 71],
    [69, 110, 73, 75],
    [68, 70, 72, 108]
])

invalid_readings = temperatures[temperatures > 100]
print(f"{len(invalid_readings)} invalid readings (above 100°F): {invalid_readings}")

fixed_temperatures = temperatures.copy()
fixed_temperatures[fixed_temperatures > 100] = 0

print(fixed_temperatures)
print(temperatures)

temperatures = np.where(temperatures > 100, 0, temperatures)
print(temperatures)

3 invalid readings (above 100°F): [105 110 108]
[[72 74  0 71]
 [69  0 73 75]
 [68 70 72  0]]
[[ 72  74 105  71]
 [ 69 110  73  75]
 [ 68  70  72 108]]
[[72 74  0 71]
 [69  0 73 75]
 [68 70 72  0]]
